@startuml

package "calc" {
    class parser <<module>> {
        + tokenize(expression: str) : list[str]
        + parse_expression(tokens: list[str]) : float
    }
}
package "app" {
    class CalculatorApp <<module>> {
        + equation_string: str
        + display_result() : void
    }
}
package "dependencies" {
    class Streamlit <<library>>
    class Selenium <<library>>
}

package "tests" {
    class TestParser <<module>> {
        + test_tokenize()
        + test_parse_expression()
    }
    class TestRobotFramework <<module>> {
        + Use Calculator One
        + Use Calculator Two
        + Use Calculator Three
        + Use Calculator Four
        + Use Calculator Five
    }
}
CalculatorApp --> parser : uses
CalculatorApp --> Streamlit : uses
TestParser --> parser : tests

@enduml
