@startuml

class Parser {
    + tokenized_expression: list[str]
    + tokenize(expression: str) : list[str]
    + parse_expression(tokens: list[str]) : float
}

class CalculatorApp {
    + equation_string: str
    + display_result()
}

class Streamlit <<library>>
class Math <<library>>

Parser --|> Math
CalculatorApp --> Parser
CalculatorApp --> Streamlit

@enduml
